In [1]:
import pandas as pd
import numpy as np

In [2]:
import statsmodels.api as sm

In [3]:
from ISLP import load_data
from ISLP.models import (ModelSpec as MS, summarize, poly)

In [4]:
rng = np.random.default_rng(1)
x = rng.normal(size = 100)
y = 2 * x + rng.normal(size = 100)

In [5]:
model = sm.OLS(y, x)
results = model.fit()
summarize(results)

      coef  std err       t  P>|t|
x1  1.9762    0.117  16.898    0.0

In [6]:
model2 = sm.OLS(x, y)
results2 = model2.fit()
summarize(results2)

      coef  std err       t  P>|t|
x1  0.3757    0.022  16.898    0.0

(c) We can see that both the part has different coef and standard errors, but t values are equal.

In [7]:
X = pd.DataFrame({'x':x})
X

           x
0   0.345584
1   0.821618
2   0.330437
3  -1.303157
4   0.905356
..       ...
95 -2.250854
96 -0.138655
97  0.033000
98 -1.425349
99  0.332814

[100 rows x 1 columns]

In [8]:
X = MS(['x']).fit_transform(X)
X

    intercept         x
0         1.0  0.345584
1         1.0  0.821618
2         1.0  0.330437
3         1.0 -1.303157
4         1.0  0.905356
..        ...       ...
95        1.0 -2.250854
96        1.0 -0.138655
97        1.0  0.033000
98        1.0 -1.425349
99        1.0  0.332814

[100 rows x 2 columns]

In [11]:
model3 = sm.OLS(y, X)
results3 = model3.fit()
summarize(results3)

             coef  std err       t  P>|t|
intercept -0.0760    0.101  -0.756  0.451
x          1.9686    0.118  16.734  0.000

In [12]:
Y = pd.DataFrame({'y':y})
Y

           y
0   0.039887
1   2.505681
2   0.535282
3  -1.937161
4   3.029555
..       ...
95 -6.119176
96  0.832327
97  0.234106
98 -2.302292
99 -0.399498

[100 rows x 1 columns]

In [14]:
Y = MS(['y']).fit_transform(Y)
Y

    intercept         y
0         1.0  0.039887
1         1.0  2.505681
2         1.0  0.535282
3         1.0 -1.937161
4         1.0  3.029555
..        ...       ...
95        1.0 -6.119176
96        1.0  0.832327
97        1.0  0.234106
98        1.0 -2.302292
99        1.0 -0.399498

[100 rows x 2 columns]

In [15]:
model4 = sm.OLS(x, Y)
results4 = model4.fit()
summarize(results4)

             coef  std err       t  P>|t|
intercept  0.0095    0.044   0.216  0.829
y          0.3763    0.022  16.734  0.000