In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [4]:
from ISLP import load_data
from ISLP.models import (ModelSpec as MS, summarize, poly)

In [2]:
rng = np.random.default_rng(234)

12(b) Example where the coefficients are not same:

In [6]:
x = rng.normal(size=100)
y = 3*x + rng.normal(size=100)

In [7]:
model1 = sm.OLS(y, x)
results1 = model1.fit()
summarize(results1)

      coef  std err       t  P>|t|
x1  2.9661    0.103  28.876    0.0

In [8]:
model2 = sm.OLS(x, y)
results2 = model2.fit()
summarize(results2)

      coef  std err       t  P>|t|
x1  0.3014     0.01  28.876    0.0

(c) Example where the coefficients are the same:

In [11]:
y = x
rng.shuffle(x)

In [12]:
np.sum(y**2) == np.sum(x**2)

np.True_

In [13]:
model3 = sm.OLS(y, x)
results3 = model3.fit()
summarize(results3)

    coef       std err             t  P>|t|
x1   1.0  4.380000e-17  2.280000e+16    0.0

In [14]:
model4 = sm.OLS(x, y)
results4 = model4.fit()
summarize(results4)

    coef       std err             t  P>|t|
x1   1.0  4.380000e-17  2.280000e+16    0.0